services:
  - type: web
    name: meesho-campus-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://campus-offer-decline-predictor-backend.onrender.com
      - key: SHEET_ID
        value: 1SXojteQ8RpbEucxXbPRd0maLlasebibw4eVbNmNqdgI
      - key: SHEET_NAME
        value: Main Tracker
